name: Task2 CI Pipeline

on:
  push:
    paths:
      - "task2-ci-cd/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      working-directory: task2-ci-cd/app
      run: pip install -r requirements.txt

    - name: Syntax Check
      working-directory: task2-ci-cd/app
      run: python -m py_compile app.py

    - name: Build Docker Image
      working-directory: task2-ci-cd/app
      run: docker build -t task2-image .
